[package]
authors = ["Twilight Contributors"]
edition = "2018"
name = "twilight-http-proxy"
version = "0.1.0"

[dependencies]
twilight-http = { version = "0.2", default_features=false, features=["rustls"]}
hyper = "0.13"
http = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["fmt", "registry"] }
tracing-log = "0.1"
reqwest = {version="0.10", default_features=false, features= ["rustls-tls"]}
snafu = "0.5"
tokio = { version = "0.2", features = ["rt-core", "macros"] }
metrics = "0.12"
metrics-observer-prometheus = "0.1"
metrics-core="0.5"
metrics-runtime = "0.13"